# Generated by Django 3.0.6 on 2020-05-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0002_auto_20200521_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='categories',
            field=models.ManyToManyField(to='Quizz.Category'),
        ),
    ]
