# Generated by Django 3.0.6 on 2020-05-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0003_auto_20200519_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possibleanswer',
            name='label',
        ),
    ]
