# Generated by Django 3.0.6 on 2020-05-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0004_remove_possibleanswer_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='answerType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quizz.AnswerType'),
        ),
    ]
