# Generated by Django 3.0.6 on 2020-05-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0005_form_ispublic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessform',
            old_name='accessFormType',
            new_name='access_form_type',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='isPublic',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answerType',
            new_name='answer_type',
        ),
        migrations.RenameField(
            model_name='useranswers',
            old_name='possibleAnswer',
            new_name='possible_answer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publicStatus',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='game',
        ),
        migrations.AddField(
            model_name='game',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizz.User'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='slot_max',
            field=models.IntegerField(default=0),
        ),
    ]
