# Generated by Django 3.0.6 on 2020-05-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0006_auto_20200522_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
