# Generated by Django 3.0.6 on 2020-05-23 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0007_auto_20200522_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='a76139ab', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Quizz.GameStatus'),
        ),
    ]
