# Generated by Django 3.0.6 on 2020-05-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0008_auto_20200523_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='83132C7A', editable=False, max_length=255, unique=True),
        ),
    ]
