# Generated by Django 3.0.6 on 2020-05-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0009_auto_20200523_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizz.User'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Quizz.GameStatus'),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='65FD8179', editable=False, max_length=255, unique=True),
        ),
    ]
