# Generated by Django 3.0.6 on 2020-05-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0011_auto_20200525_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_real_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='BC2639C5', editable=False, max_length=255, unique=True),
        ),
    ]
