# Generated by Django 3.0.6 on 2020-05-31 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0013_auto_20200531_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_random_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='A7AE1795', editable=False, max_length=255, unique=True),
        ),
    ]
