# Generated by Django 3.0.6 on 2020-06-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0014_auto_20200531_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2020-05-23 13:13:55'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='8E9FC809', editable=False, max_length=255, unique=True),
        ),
    ]
