# Generated by Django 3.0.6 on 2020-06-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0015_auto_20200601_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_invited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='bad_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='good_answer',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='6A9CD27D', editable=False, max_length=255, unique=True),
        ),
    ]
