# Generated by Django 3.0.6 on 2020-06-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0016_auto_20200603_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='need_correction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='5B5CE694', editable=False, max_length=255, unique=True),
        ),
    ]
