# Generated by Django 3.0.6 on 2020-06-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0017_auto_20200605_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='uuid',
            field=models.CharField(default='48D67F91', editable=False, max_length=255, unique=True),
        ),
    ]
