# Generated by Django 3.0.6 on 2020-06-10 00:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0019_auto_20200609_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_limited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='time_launched',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='timer',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
