# Generated by Django 3.0.6 on 2020-06-10 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0020_auto_20200610_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='actual_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Quizz.Question'),
        ),
    ]
