# Generated by Django 3.0.6 on 2020-06-10 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0021_form_is_older_version'),
        ('Quizz', '0021_game_actual_question'),
    ]

    operations = [
    ]
