# Generated by Django 3.0.6 on 2020-06-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0022_merge_20200610_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='actual_question',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
