# Generated by Django 3.0.6 on 2020-06-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0023_auto_20200610_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
