# Generated by Django 3.0.6 on 2020-06-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quizz', '0024_form_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='is_deleted',
            new_name='is_hidden',
        ),
    ]
